name = "CTtoDFM"
authors = [
    "Carlos Ferreira",
    "Nick Hamidreza",
]
interface = "Python code"
input_data = """
Pre-processing within `CTtoDFM` includes meshing a
point cloud of the fractures from the CT scan along with many more steps
(Figure @fig:cttodfm_workflow) listed in the `README.md` of the repository.

![Workflow of `CTtoDFM` from CT images to fracture and flow modelling. Image
from
@ferreira_computed-tomography-based_2023.](src/images/cttodfm_workflow.jpg){#fig:cttodfm_workflow}
"""
outputs = """
3D-images of the results can be saved in `vtk` format for viewing in
visualization software. Furthermore, the "shape" of the models is saved in text
files (`txt`).
"""
remarks = """
`CTtoDFM` is specialized for the creation of integrated discrete
fracture-matrix models based on 3D CT scan images (`tiff` files) of rock
volumes. Consequently, it is not useful for general scenarios of, e.g.,
DFN-modelling but rather for cases where CT scanning of rock samples is
possible. Use of the software requires `Rhinoceros 4.0` and `Ansys ICEM CFD`,
i.e., while the code is open, using it fully requires proprietary licenses.
"""
license = "Unknown"

[url]
repository = "https://gitlab.gbar.dtu.dk/offshore/CTtoDFM/"
documentation = "https://gitlab.gbar.dtu.dk/offshore/CTtoDFM/"
reference = "https://doi.org/10.1016/j.advwatres.2023.104450"
forum = ""

[state_of_documentation]
installation = """
Installation instructions are provided for Windows 10. Multiple software
programs need to be installed including `Docker` for Windows.
"""
usage = """
Usage instructions consist of Python code and command line examples that
describe the workflow from CT scans to modelling (Figure
@fig:cttodfm_workflow). The workflow uses multiple software programs to reach
the end result, i.e., the process is somewhat complex and manual.
"""
examples = """
The repository `README.md` describes an example workflow but the input data for
the workflow is not provided.
"""

[capabilities]
based_on_documentation = """
The reference article and repository `README.md` describe a workflow from
computer tomography (CT)
scan images to fracture and flow modelling. End results of the modelling
include fracture network and permeability visualizations and tensors of
permeability (Figure @fig:cttodfm_permeability_tensors).

![Permeability tensors produced as an end product of `CTtoDFM` flow modelling.
Image from
@ferreira_computed-tomography-based_2023.](src/images/cttodfm_permeability_tensors.jpg){#fig:cttodfm_permeability_tensors}
"""
based_on_testing = """
"""
